### ISSUE TITLE
Nether gold ore isn't glowing

### ISSUE THREAD

**Issue by MaoYan5985** [ComplementaryDevelopment/ComplementaryShadersV4#10]
![1](https://github.com/ComplementaryDevelopment/ComplementaryShadersV4/assets/122714639/971e9ddd-1e7a-417a-85f1-b97528290ec7)
As the image shown, normal gold ore and diamond ore are glowing. But the nether gold ore isn't glowing.

- MC : 1.20.1
- ComplementaryShaders_v4.7.2
- Iris 1.6.7

**Comment by EminGT** [comment]
"Glowing Nether Ores" is an optional effect found in Shader Settings
