### ISSUE TITLE
Mekanism's Advanced bin display

### ISSUE THREAD

**Issue by djzg** [ComplementaryDevelopment/ComplementaryShadersV4#4]
Hi guys, not sure if this is the right place. I've asked on the discord and couldn't solve it, I guess it's a bug of some sort. Perhaps, it would be interesting to look at?

I'm running a Manufactio modpack that includes Mekanism mod, all on Minecraft version 1.12.2. 
I've installed ComplementaryShaders_v4.7.1 and I also have Optifine 1.12.2 HD U G6.

Everything looks fine except Advanced bins from Mekanism mod. Item displayed is barely visible, it only shows the black outline. I've tried messing with settings for two days but without improvement. I've also tried BSL shaders and the item outline is a bit brighter but still blackened out. 

I'm attaching a few screenshots. Let me know if there are any other details for me to provide.

Thanks for your time and help.

![mc_prtscn1](https://user-images.githubusercontent.com/12217840/216446530-1bc57a0a-2ad3-4064-bf17-b3b2434eda41.png)
![mc_prtscn3](https://user-images.githubusercontent.com/12217840/216446548-09ef13a6-61f4-4ab8-a5c5-0f0081c20f8d.png)
![mc_prtscn4](https://user-images.githubusercontent.com/12217840/216446555-387d99e5-1396-4f6b-90bd-bf312fbeffb3.png)

**Comment by EminGT** [comment]
Hello. Unfortunately the problem is caused by incorrect color values being
passed from the mod to the shaderpack. I don't think we can do much about
it on the shader side.

**Comment by djzg** [comment]
That's a shame. Have you tried in the past contacting the devs of Mekanism to try and repair it?
I'd open an issue on their github page but it might have more weight coming from you?

**Comment by EminGT** [comment]
I don't want to open an issue myself when I don't have time to test and report about the problem further. It's more up to the users to report problems that they are having, as this problem doesn't have much to do with me. I'm sorry

**Comment by djzg** [comment]
No worries man, sorry for dropping with the request. I was assuming there might already be some solution you've tried with them in past. 
I'll open an issue on their github, won't be a problem, especially if it's solved. 
Do you perhaps have an exact line of code that causes this bug so that I can pinpoint them the exact problem?

**Comment by EminGT** [comment]
Unfortunately no. I don't know much about mod coding, as shaders work quite
a bit differently
