### ISSUE TITLE
reflection problem

### ISSUE THREAD

**Issue by Experienced-Butter** [ComplementaryDevelopment/ComplementaryShadersV4#6]
there are some problems with the reflection of smooth surface
for example
![2023-06-25_03 37 06](https://github.com/ComplementaryDevelopment/ComplementaryShadersV4/assets/88971052/2f954caf-b88b-41b9-b8a9-f436c701f3c2)
in this picture,the real fire and the reflection fire are all correctly shown

but,if I move my head a little up,and let the root of the real fire get out from the camera
![2023-06-25_03 40 56](https://github.com/ComplementaryDevelopment/ComplementaryShadersV4/assets/88971052/5df2cd8d-ace2-492a-98ae-763a7c59fdab)
you see? the root of the reflection fire disappeared too!
in the real world,whether I can see the real fire or not,I can always see the whole refrection fire

the same problem also appeared on water and metal reflection

I wish you can fix it as soon as possible.

**Comment by tajemniktv** [comment]
I'd say that it's not an *issue* per se, but a effect of using screen space reflections and not something else. As something else would decrease performance by... well, a lot most likely

**Comment by EminGT** [comment]
It's just a limitation of the way reflections are done
